### ISSUE TITLE
Admin GUI not accessible

### ISSUE THREAD

**Issue by ghost** [digitalocean/OpenVPN-Pihole#10]
Aloha,
i just created an openvpn + pihole droplet. 
Since the update to PiHole 5.0, the Admin GUI is not accessible, neither via "pi.hole/admin" or the droplet IP. Nevertheless, access is possible via `10.8.0.1/admin` 
After changing the the nameserver in `/etc/resolv.conf` from `127.0.0.53` to, for example, google's or cloudflare's DNS, the GUI can be reached again under `pi.hole/admin`. 

furthermore it was not possible to add a blocklist to the adlist before the change. 

> Error, something went wrong! 

> While executing: attempt to write a readonly database 

> Added 0 out of 1 adlists 

after changing the nameserver, this was possible again.  

greetings

**Comment by tech42676** [comment]
Same issue, pi.hole/admin does not work

**Comment by sacmii** [comment]
Any solution ?

**Comment by ghost** [comment]
> Any solution ?

@sacmii try that [Link](https://github.com/digitalocean/OpenVPN-Pihole/issues/12#issue-627775388)

**Comment by CrashenX** [comment]
Thanks for reporting this! Sorry for the delayed response. This was a hackathon project, and due to COVID I haven't used it much lately (been at home and leveraging my local install). I'll try to take a look at this or find someone who can.

**Comment by CrashenX** [comment]
I was able to reproduce. Let me see if I can get a quick fix together.

**Comment by CrashenX** [comment]
I have a PR up that should fix this. I did some initial testing, but need to rebuild the image, verify it works as expected, and then push it up to be used on marketplace creates. You can use the change in the PR as a workaround in the meantime.

**Comment by CrashenX** [comment]
The marketplace image has been updated. Thanks for reporting this, and sorry again for the delay.
