### ISSUE TITLE
How to assign Floating IP?

### ISSUE THREAD

**Issue by himanshuahuja96** [digitalocean/OpenVPN-Pihole#11]
Can you please add a guide for floating ip?

**Comment by CrashenX** [comment]
Thanks for reporting this. I'll have to test this out with floating IP, and add some docs.

**Comment by CrashenX** [comment]
So I never got around to this, and I'm likely to anytime soon. If you figured it out and wanna make a PR, I can review / test it.

**Comment by CrashenX** [comment]
@himanshuahuja96 Working to create a new image. I can test with floating ip.

**Comment by CrashenX** [comment]
The new image is up: https://github.com/digitalocean/marketplace-pi-hole-vpn

I haven't tested with floating ip yet, but it's on my list.

**Comment by CrashenX** [comment]
Tested. Works. Add note to README here: https://github.com/digitalocean/marketplace-pi-hole-vpn#use-it
