### ISSUE TITLE
Droplet dns not using pihole by default

### ISSUE THREAD

**Issue by linted** [digitalocean/OpenVPN-Pihole#12]
# Overview
When a new droplet is created, the default resolver is set to `127.0.0.53` by `systemd-resolve`. This causes networking to not work correctly for the pihole daemon and root user. 

# Why does this matter?
Since the pihole deamon can't resolve dns, gravity fails to update. This means that no new blocked domains will be automatically pulled in. It also stops apt updates from working correctly as well, leaving the system in a more vulnerable state.

# How can this be fixed?
Change the default resolver from being `systemd-resolve` to pihole's dns resolver. A manual fix for this issue involves editing `/etc/resolve.conf`to perform dns resolution against `127.0.0.1`.

**Comment by NikeLaosClericus** [comment]
I'm having the same issue, but the proposed fix isn't working for me.

**Comment by ghost** [comment]
@NikeLaosClericus try `sudo nano /etc/resolve.conf` after the dns change, continue with`pihole -r` and select `repair`

**Comment by linted** [comment]
How do we make this into a permanent change? modifying `/etc/resolve.conf` only works until next reboot. The droplet should also have that setting by default so users don't have to know to make that change.

**Comment by ghost** [comment]
Found another way to fix the reboot problem. Add a line with `Nameserver 127.0.0.1` to `/etc/resolvconf/resolv.conf.d/tail`

**Comment by CrashenX** [comment]
Hey, thanks for reporting this. Sorry for the delayed response. I think this might be a duplicate of: https://github.com/digitalocean/OpenVPN-Pihole/issues/10

**Comment by CrashenX** [comment]
I have a PR up that should fix this. I did some initial testing, but need to rebuild the image, verify it works as expected, and then push it up to be used on marketplace creates. You can use the change in the PR as a workaround in the meantime.

@0x686b My solution is similar to your recommendation (I modified head).

**Comment by CrashenX** [comment]
The marketplace image has been updated. Thanks for reporting this, and sorry again for the delay.
