### ISSUE TITLE
Request to Add YouTube updater for Pi-hole

### ISSUE THREAD

**Issue by raj0x29** [digitalocean/OpenVPN-Pihole#15]
Here is the repo https://gitlab.com/grublets/youtube-updater-for-pi-hole

YouTube updater for Pi-hole

Quick and dirty script that may help with YouTube ads.

This is not ideal and not as good as running a proper ad blocker in a
browser, but for things like AppleTV it seems to work well enough. Every
time an ad slips through, it adds the offending hostname to the
hosts file in which we force an IP of our choosing.

N.B. You must block outgoing DNS from anything but your Pi-holes for maximum
effectiveness (even better, redirect to your Pi-hole!)
Some apps have hard-coded DNS servers that will bypass your Pi-hole.
If you don't do this then use the script, please don't complain about ads
in, for example, your Samsung TV's YouTube app.
Read the manual for your network gateway device.

Avoid updating any official YouTube apps if possible.

### Install

**\[Do all these as root\]**

01 - Download the script to a sane area eg.: /usr/local/bin

02 - Make it executable. "chmod a+x youtube.update.sh"

*\[steps 03-06 ensure you are using a geoip'd IP close to where you are\]*

03 - Use the Pi-hole's "Query Log" function and seach for "googlevideo.com".

04 - Look for a hostname similar to "r6---sn-ni5f-tfbl.googlevideo.com" It won't match the example, but you will know one when you see one. You will likely have many matches, pick one at random. If you don't see any, watch some YouTube! :)

05 - Perform a name lookup on that hostname you found eg.: "nslookup r6---sn-ni5f-tfbl.googlevideo.com"

06 - Copy the IPv4 IP address it returns.

07 - Edit the script, change the forceIP="123.456.789.999" to the real numbers you copied in step 5.

08 - Save it.

09 - Execute the script for the first time "./youtube.update.sh"

10 - Restart Pi-hole DNS "pihole restartdns"

11 - Automate it to run every minute for constant updates as new things slip through. I did mine in cron. "man cron" if you don't know how.

**Comment by CrashenX** [comment]
I pay for YouTube premium so I'm unlikely to do any work on this enhancement. I think a potential path forward here would be to write a post-install script for people to use. Maintain it on github, and make a PR to the docs in this repo.

**Comment by CrashenX** [comment]
A successor to this image has been created: https://github.com/digitalocean/marketplace-pi-hole-vpn/blob/main/README.md

I didn't end up adding this enhancement and I don't think I'm going to. Why?
- I believe if you are going to use a service frequently and you don't want ads, you should consider donating / paying for their service to incentivize revenue models that are not ad-based. Blocking youtube ads here just makes the problem worse IMHO
- Whether you decide to pay for YouTube Premium or not, there's always NewPipe: https://newpipe.net/
