### ISSUE TITLE
I can't create additional client configuration 

### ISSUE THREAD

**Issue by Ahmedmud** [digitalocean/OpenVPN-Pihole#18]
I have launched a new OpenVPN-Pihole server in Digital Ocean and it is really running perfectly with the the existing client.opvn client config file. However, when I try to add a new config file I get the following error:

"root@myserver:~# create-client-config.sh client2
create-client-config.sh: command not found"

I made sure that the command is there by listing the directory 

"root@myserver:~# ls
client.ovpn  create-client-config.sh"

Please advise

**Comment by merwok** [comment]
For security, shells don’t look in the current directory for commands, only on the directories listed in the PATH environment variables.

To run a command from a non-PATH directory, it needs to be a path, for example: `./create-client-config.sh` (this is a path relative to current directory).  The file also needs to be executable (check with `ls -hla`, change if needed with `chmod +x create-client-config.sh`).

**Comment by Ahmedmud** [comment]
Thanks merwok

`./create-client-config.sh` solved the issue

**Comment by Ahmedmud** [comment]
Thanks merwok
