### ISSUE TITLE
Guide to Renew SSL and Updates

### ISSUE THREAD

**Issue by himanshuahuja96** [digitalocean/OpenVPN-Pihole#19]
We have our VPN IP whitelisted in our Client network, so we have to renew and update the existing to work with them.

Can you help putting a guide for this?

**Comment by CrashenX** [comment]
OpenVPN cert renewal should be well documented. I'd just be copy pasting information that's maintained elsewhere.

This tool was mostly designed for road warriors who temporarily need a pi hole server when away from home and wasn't meant to be a long-lived server. Therefore, it was designed with the ideal that you would delete and recreate servers on demand and not renew.
