### ISSUE TITLE
IPV6 ?

### ISSUE THREAD

**Issue by wilksy** [digitalocean/OpenVPN-Pihole#2]

**Comment by CrashenX** [comment]
As in connect to VPN over IPV6 or IPV6 based ad blocking?

**Comment by sundowndev** [comment]
+1
connection over IPV6 should be supported

**Comment by CrashenX** [comment]
It looks like Nyr updated OpenVPN RoadWarrior to support IPV6: https://github.com/Nyr/openvpn-install/commit/5229459f99c5204f59697f880508f05cbb6d3999 so this should be easier to support now (given it's based off of it).

**Comment by veeramuthub** [comment]
+1 requesting ipv6 after install

**Comment by CrashenX** [comment]
When I get time to make meaningful changes to this image, I'll probably switch to wireguard and make sure to verify ipv6 works at that time.

**Comment by sundowndev** [comment]
> When I get time to make meaningful changes to this image, I'll probably switch to wireguard and make sure to verify ipv6 works at that time.

@CrashenX  I switched to wg a while ago and it works fine, I recommend using [algo](https://github.com/trailofbits/algo).

**Comment by CrashenX** [comment]
The new image is not posted to the marketplace yet, but working to get it up there ASAP. In the meantime, you can create your own snapshot and build droplets from that: https://github.com/digitalocean/marketplace-pi-hole-vpn
