### ISSUE TITLE
VPN Up Script Grabs Wrong IP

### ISSUE THREAD

**Issue by CrashenX** [digitalocean/OpenVPN-Pihole#21]
All Droplets get a private network by default now. This results in the script grabbing the private IP instead of the public one. Pretty easy fix here: https://github.com/digitalocean/OpenVPN-Pihole/blob/master/client-tools/vpn-up#L82

Just need to update and validate. Not sure it's always IP 2 though so probably need to check for not a 10. address or alternate between trying to ssh into each address.

**Comment by kindaran** [comment]
If I remember/get time this weekend I'll have a look at this. I'm curious if I can just loop through that specific part of the response, if the public ip won't always be in the same position. I'll also have to figure out how to actually go through the code change process... I've never contributed before :)

**Comment by kindaran** [comment]
Here is my proposed change.

Existing code to retrieve new Droplet IP address:
`IP="$(echo "$DROPLET" | jq -r '.droplet.networks.v4[0].ip_address')"`

Proposed change:
`IP="$(echo "$DROPLET" | jq -r '.droplet.networks.v4[] | select(.type=="public") | .ip_address')"`

The changed code modifies the jq processing. The logic changes from:

> "select key "ip_address" from array element at index 0 within the JSON structure at droplet.networks.v4"

to

> "select key "ip_address" from array element that has the key "type" equal to the value "public" within the JSON structure at droplet.network.v4"

In reviewing the JSON payload, I noticed the key value "type" in each network.v4 array element and that the IP address desired has the type value of "public".

I have tested this in the full vpn-up script using two different regions (toronto, NYC) just in case there might be some difference in JSON content. Given the specificity of the scripting, I dont know that more "exotic" testing would be of value (i.e. testing outside the bounds of creating an OpenVPN-PiHole server, with a specific image, etc). 

Let me know what you think and if there might be more testing to try.

**Comment by CrashenX** [comment]
@kindaran I tested your suggested change and it LGTM. If you want to fork the repo, commit your changes, and make a PR to master of this repo, I can review and approve.

I also recommend you run the updated script through shellcheck.

**Comment by kindaran** [comment]
I'll see what I can do. I am hoping there is no way that I can screw up your repo :)

**Comment by CrashenX** [comment]
You cannot :)

**Comment by kindaran** [comment]
Speaking of pull requests.... hey look, there's a request for this issue! :)

**Comment by CrashenX** [comment]
@kindaran Thanks for the contribution and sorry for the delay reviewing!
