### ISSUE TITLE
Pihole 1.1.1 version does not connect

### ISSUE THREAD

**Issue by pachadotdev** [digitalocean/OpenVPN-Pihole#22]
error message: `ERROR: Cannot ioctl TUNSETIFF tun: Operation not permitted (errno=1)`

**Comment by kindaran** [comment]
What steps are you taking prior to receiving this error? Are you attempting to start openvpn?

**Comment by pachadotdev** [comment]
> What steps are you taking prior to receiving this error? Are you attempting to start openvpn?

on Ubuntu I typed ` sudo openvpn --config client.ovpn`, it used to work a few weeks ago
it works on Android with the openvpn client application

**Comment by kindaran** [comment]
What are you trying to do with the --config option? When I execute the command I get an error "Unrecognized option or missing or extra parameter(s)" and then openvpn attempts a connect using the .ovpn file. And --config does not show up as an option ("openvpn --help").

Also, I get a bunch of output (of course, my server/connection is working). Can you paste all the output you get starting from the prompt where you entered the command?

**Comment by pachadotdev** [comment]
thanks, I get
```
OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 14 2019
library versions: OpenSSL 1.1.1  11 Sep 2018, LZO 2.08
Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
TCP/UDP: Preserving recently used remote address: [AF_INET]REDACTED:1194
Socket Buffers: R=[212992->212992] S=[212992->212992]
UDP link local: (not bound)
UDP link remote: [AF_INET]REDACTED:1194
TLS: Initial packet from [AF_INET]REDACTED:1194, sid=2dbd0047 985044f2
VERIFY OK: depth=1, CN=ChangeMe
VERIFY KU OK
Validating certificate extended key usage
++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
VERIFY EKU OK
VERIFY OK: depth=0, CN=server
Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 2048 bit RSA
[server] Peer Connection Initiated with [AF_INET]REDACTED:1194
SENT CONTROL [server]: 'PUSH_REQUEST' (status=1)
PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1 bypass-dhcp,dhcp-option DNS 10.8.0.1,route-gateway 10.8.0.1,topology subnet,ping 10,ping-restart 120,ifconfig 10.8.0.2 255.255.255.0,peer-id 0,cipher AES-256-GCM'
OPTIONS IMPORT: timers and/or timeouts modified
OPTIONS IMPORT: --ifconfig/up options modified
OPTIONS IMPORT: route options modified
OPTIONS IMPORT: route-related options modified
OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
OPTIONS IMPORT: peer-id set
OPTIONS IMPORT: adjusting link_mtu to 1624
OPTIONS IMPORT: data channel crypto options modified
Data Channel: using negotiated cipher 'AES-256-GCM'
Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
ROUTE_GATEWAY 192.168.0.1/255.255.255.0 IFACE=wlp2s0 HWADDR=REDACTED
ERROR: Cannot ioctl TUNSETIFF tun: Operation not permitted (errno=1)
```

**Comment by kindaran** [comment]
Interesting. My ROUTE_GATEWAY output is:
`Sun Oct 18 12:16:14 2020 ROUTE_GATEWAY 10.8.0.1/255.255.255.0 IFACE=tun0 HWADDR=[]`
The IP address is an internal address on DO. Whereas your address looks like it could be your own network. Also my IFACE parameter is different.

I think the rest of your output pretty much matches what I see.

**Comment by kindaran** [comment]
Unfortunately I'm still new to this so not at all an expert. Mostly trying to get some information from you to help others solve the problem (i.e. making sure you provide as much info as possible: what steps led to the error, can you repeat it, provide any output and/or logs, etc.)

Another question to ask: I assume you setup a DigitalOcean server using the OpenVPN+PiHole from the marketplace. I assume you made no further changes on the new server. I assume the client.ovpn file is what was downloaded during the server setup and you have made no changes to it. When did you setup the DO server?

**Comment by pachadotdev** [comment]
hi
thanks. yes, I made no changes to the server and it was created today from
the marketplace

—————

*Mauricio Vargas Sepúlveda 帕夏*
Do you like Data Science? visit pacha.hk
你爱科学数据专吗？你走pacha.hk
