### ISSUE TITLE
How do I setup the VPN?

### ISSUE THREAD

**Issue by TheEpicFace007** [digitalocean/OpenVPN-Pihole#24]
I installed the droplet with this config. How do I set it up? I am confused

**Comment by kindaran** [comment]
Did you follow the information under "Getting started after deploying OpenVPN + Pihole" on page [https://marketplace.digitalocean.com/apps/openvpn-pihole](url)

**Comment by TheEpicFace007** [comment]
Yes but I didn’t understood

**Comment by kindaran** [comment]
Please provide the steps you took to create the droplet. How did you create it? Just through the Digital Ocean marketplace? Did you use the vpn-up script that is part of this repository? What have you done so far and where are you not understanding something?

**Comment by TheEpicFace007** [comment]
I created it using through the digital ocean marketplace

**Comment by kindaran** [comment]
Need a bit more detail. You picked a droplet config and used the marketplace to pick OpenVPN-PiHole image? What next? Did you login to the server and download the client.ovpn file? 

Using the vpn-up script in the repository, client-tools directory automates things a little bit but the current script needs a couple of edits to work ideally.

**Comment by TheEpicFace007** [comment]
while doing the inital configuration, I selected the opencvpn pihole config

**Comment by kindaran** [comment]
And did you connect to the server in order to download the client.ovpn file?

How much linux knowledge do you have?

**Comment by TheEpicFace007** [comment]
no I didn't

as for my knowledge on gnu+linux,; I know the basic command such as ls, downloading a package and updating packages, mkdir, touch

**Comment by kindaran** [comment]
Login as root using ssh. I'm assuming you created a root password? Client.ovpn is in directory ~

You can also try using scp or use an ftp app.

Note that the VPN-up script in the githhub repository makes this a bit easier though you need to make a couple of edits to the script

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by dvasbva1** [comment]
> ftp app.

This is the way to go for users with limited linux experience.

**Comment by TheEpicFace007** [comment]
ok
