### ISSUE TITLE
VPN Configuration page missing

### ISSUE THREAD

**Issue by jackcrane** [digitalocean/OpenVPN-Pihole#25]
Hallo! 

I just spun up the VM, and found that I am able to connect to the VPN etc, but I cannot edit the VPN config page (https://openvpn.net/vpn-server-resources/how-to-configure-openvpn-as-with-admin-web-ui/). I then tried to use OpenVPN's steps for troubleshooting (https://openvpn.net/vpn-server-resources/troubleshooting-access-to-the-web-interface/), but to no avail.

Upon further investigation, I was unable to find the `./sacli` app.

Any tips?

**Comment by kindaran** [comment]
I havent tried to access that (this is my first droplet with this config). Just follow the Getting Started stuff at [https://marketplace.digitalocean.com/apps/openvpn-pihole](url)
