### ISSUE TITLE
Client cannot connect to my server. 

### ISSUE THREAD

**Issue by RedGamingBlue** [digitalocean/OpenVPN-Pihole#26]
I am currently connected to my server and he cannot connect. We have tried it when I was disconnected and everything. It was working last night now it has stopped working for him. I have created multiple profiles none of which have worked. When he runs it through openvpn gui it returns with this:
Wed Dec 16 09:27:18 2020 OpenVPN 2.5_rc3 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Oct 19 2020
Wed Dec 16 09:27:18 2020 Windows version 10.0 (Windows 10 or greater) 64bit
Wed Dec 16 09:27:18 2020 library versions: OpenSSL 1.1.1h 22 Sep 2020, LZO 2.10
Wed Dec 16 09:27:18 2020 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:25341
Wed Dec 16 09:27:18 2020 Need hold release from management interface, waiting...
Wed Dec 16 09:27:18 2020 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:25341
Wed Dec 16 09:27:19 2020 MANAGEMENT: CMD 'state on'
Wed Dec 16 09:27:19 2020 MANAGEMENT: CMD 'log all on'
Wed Dec 16 09:27:19 2020 MANAGEMENT: CMD 'echo all on'
Wed Dec 16 09:27:19 2020 MANAGEMENT: CMD 'bytecount 5'
Wed Dec 16 09:27:19 2020 MANAGEMENT: CMD 'hold off'
Wed Dec 16 09:27:19 2020 MANAGEMENT: CMD 'hold release'
Wed Dec 16 09:27:19 2020 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Wed Dec 16 09:27:19 2020 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Wed Dec 16 09:27:19 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]138.197.200.203:1194
Wed Dec 16 09:27:19 2020 Socket Buffers: R=[65536->65536] S=[65536->65536]
Wed Dec 16 09:27:19 2020 UDP link local: (not bound)
Wed Dec 16 09:27:19 2020 UDP link remote: [AF_INET]138.197.200.203:1194
Wed Dec 16 09:27:19 2020 MANAGEMENT: >STATE:1608139639,WAIT,,,,,,

After it says that, it just sits there and repeats itself. Anyone know how to fix this? Thanks!

**Comment by CrashenX** [comment]
Sorry I didn't get to this until now =/

If you're still having issues lmk. I've never had issues connecting multiple clients.
