### ISSUE TITLE
Can't access to web server

### ISSUE THREAD

**Issue by mrbungle1903** [digitalocean/OpenVPN-Pihole#29]
I made the installation according to the instructions, everything went OK and pihole is running (pihole status command returns successfully). But I cannot access to webserver. I am using Windows 11, OpenVPN is also the latest one from October 5th. Is there a fix for that or maybe a compatibility issue within?

**Comment by CrashenX** [comment]
I just created a new droplet from the marketplace image using [this script](https://github.com/digitalocean/OpenVPN-Pihole/blob/master/client-tools/vpn-up). I connected with the OpenVPN Android client and everything is working.  I only use this on Android, and not really a Windows user so hard for me to test on Windows. It should be OS agnostic though. You just need to import the client.ovpn file into the OpenVPN client.
