### ISSUE TITLE
4$ dollar tier support

### ISSUE THREAD

**Issue by Noisycall** [digitalocean/OpenVPN-Pihole#33]
Hi
Is it possible for this app to support the $4 tier of digital ocean? It functions well as a persistent VPN for 1 or 2 devices, and now that the price of a default tier has gone up to $6, I was wondering if it would be possible to deploy this to a lower tier.
Thanks

**Comment by CrashenX** [comment]
@Noisycall Working to update to Jammy. Will be using $4 Droplet during creation / testing. 🤞

**Comment by CrashenX** [comment]
The new image is not posted to the marketplace yet, but working to get it up there ASAP. In the meantime, you can create your own snapshot and build droplets from that: https://github.com/digitalocean/marketplace-pi-hole-vpn
