### ISSUE TITLE
PiHole not available in Droplet

### ISSUE THREAD

**Issue by mr-pink** [digitalocean/OpenVPN-Pihole#34]
Dear all,
due to the 90d validity-policy of the OpenVPN certs, I recently destroyed and redeployed my DigitialOcean droplet (1 GB mem, 25 GB disk, hosted in FRA1) and now face the absence of the PiHole-component -- the OpenVPN-component works, I can create certs and see connected clients in the logs. When I SSH into the droplet, I cannot see PiHole running in the list of services. Neither does the "pihole" command set seem to be available. It all looks like the entire component is not installed and running.

I deployed the droplet via the DigitialOcean Marketplace on 2022-09-03 1pm CEST. 
Could someone please have a look, share their experience, or provide hints on how to fix this, please? Since the entire setup seems to rely on PiHole providing the DNS, also the OpenVPN-component is not usable, unfortunately.
Thanks allot in advance!
Best regards
Oliver

**Comment by jar-dog** [comment]
I can confirm as well, I've spun up a couple of droplets this morning (11 Sept. 2022) in the NYC data center with same problem.  OpenVPN installs and sets up properly, but there isn't an accompanying pi-hole install on the marketplace image.

Thanks,
jarman

**Comment by CrashenX** [comment]
@jar-dog @mr-pink Working to update image to Jammy

**Comment by CrashenX** [comment]
The new image is not posted to the marketplace yet, but working to get it up there ASAP. In the meantime, you can create your own snapshot and build droplets from that: https://github.com/digitalocean/marketplace-pi-hole-vpn
