### ISSUE TITLE
Revoke client certificate

### ISSUE THREAD

**Issue by robinsonjohn** [digitalocean/OpenVPN-Pihole#35]
As per the documentation, new clients are created using `/root/create-client-config.sh CLIENT_NAME`

How would one go about revoking a client?

**Comment by CrashenX** [comment]
I'm working on a new image to replace this one which makes VPN setup and configuration easier. Revocation in that image can be done by regenerating keys or just dropping the peer from the config file.

https://github.com/digitalocean/marketplace-pi-hole-vpn

**Comment by robinsonjohn** [comment]
@CrashenX Thank you for the update, and for your contribution to the DO Marketplace. Much appreciated!

**Comment by CrashenX** [comment]
@robinsonjohn NP! Hoping to launch the new image in the next few days. in the meantime if you're interested, you can build your own based off my PR here: https://github.com/digitalocean/marketplace-pi-hole-vpn/pull/1/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by CrashenX** [comment]
The new image is not posted to the marketplace yet, but working to get it up there ASAP. In the meantime, you can create your own snapshot and build droplets from that: https://github.com/digitalocean/marketplace-pi-hole-vpn
