### ISSUE TITLE
Updating Pi-Hole

### ISSUE THREAD

**Issue by robinsonjohn** [digitalocean/OpenVPN-Pihole#36]
When updating to the latest version of Pi-Hole using `pihole -up`, the following message is shown:

`Unsupported OS detected: Ubuntu 18.04`

Once force continuing with the command `sudo PIHOLE_SKIP_OS_CHECK=true pihole -r`, FTL does not seem to start.

**Comment by CrashenX** [comment]
@robinsonjohn Working to update to Jammy.

**Comment by CrashenX** [comment]
The new image is not posted to the marketplace yet, but working to get it up there ASAP. In the meantime, you can create your own snapshot and build droplets from that: https://github.com/digitalocean/marketplace-pi-hole-vpn
