### ISSUE TITLE
Pi-hole doesn't support Ubuntu 18.04, please modify the digital ocean solution in marketplace

### ISSUE THREAD

**Issue by ovchinnikoff** [digitalocean/OpenVPN-Pihole#37]
Hello.

First of all, thank you for your solution! It helps many people in those difficult times. Thank you!

Pi-hole + OpenVPN solution in digital ocean doesn't work now and I think that the reason is this https://discourse.pi-hole.net/t/psa-dropping-support-for-ubuntu-18-04/57523

Could you please fix your solution in Digital Ocean marketplace?

**Comment by CrashenX** [comment]
@ovchinnikoff Working to update to Jammy.

**Comment by CrashenX** [comment]
The new image is not posted to the marketplace yet, but working to get it up there ASAP. In the meantime, you can create your own snapshot and build droplets from that: https://github.com/digitalocean/marketplace-pi-hole-vpn
