### ISSUE TITLE
Command 'pihole' not found

### ISSUE THREAD

**Issue by jeronimofagundes** [digitalocean/OpenVPN-Pihole#6]
Hi, I've just created a droplet at DigitalOcean with this image. In the instructions, it says:

> To set / reset the admin password run:
>    pihole -a -p

However, when I run the command, I got this:

> root@openvpn-pihole-ubuntu-s-1vcpu-1gb-nyc1-01:~# pihole -a -p
> 
> Command 'pihole' not found, did you mean:
> 
>   command 'pahole' from deb dwarves
> 
> Try: apt install <deb name>
> 
> 

Thanks in advance.

**Comment by CrashenX** [comment]
You created it via the Marketplace: https://cloud.digitalocean.com/marketplace/5d8e460e547de16703cd8817 ?

I just created one and the command worked fine. I suspect what is happening here is that you tried too quickly. Both OpenVPN and Pihole are installed on first boot (just after droplet creation). If you ssh right after creation, OpenVPN and Pihole may have still been installing. You can also take a look in `/var/log` and check the pihole logs to see if it's still in progress or if something went awry. During installation `client.ovpn` and `create-client-config.sh` are placed in `/root` as part of the OpenVPN install. Pihole should be installed just after those show up.

Let me know if you're still having issues after giving it a few minutes.

**Comment by jeronimofagundes** [comment]
> You created it via the Marketplace: https://cloud.digitalocean.com/marketplace/5d8e460e547de16703cd8817 ?

Yes!

> I just created one and the command worked fine. I suspect what is happening here is that you tried too quickly. Both OpenVPN and Pihole are installed on first boot (just after droplet creation). If you ssh right after creation, OpenVPN and Pihole may have still been installing. You can also take a look in `/var/log` and check the pihole logs to see if it's still in progress or if something went awry. During installation `client.ovpn` and `create-client-config.sh` are placed in `/root` as part of the OpenVPN install. Pihole should be installed just after those show up.
> 
> Let me know if you're still having issues after giving it a few minutes.

You were right, waiting some 5 to 10 minutes it worked. Maybe it is a good idea to add this information to motd?

**Comment by CrashenX** [comment]
Totes. I can add that when I do a new build.
