### ISSUE TITLE
Unable to use Pi-hole dns without vpn?

### ISSUE THREAD

**Issue by real-stone** [digitalocean/OpenVPN-Pihole#9]
Hello i just create droplet on D.ocean which pre-compiled pic below of openvpn+pihole, my problem is, i want to use pihole both side let suppose i want to use pihole as DNS server on my home pc, and with .ovpn file on my mobile phone unfortunately my pc not working with just putting dns address that is 10.0.8.x.x but the other side when i connect my mobile with client file .ovpn with openvpn connect client it works perfect.I tried my vps server ip i.e 142.x.x.x and dns on my pc but same issue dns server isn’t respond. then i download openvpn client for pc the connect with that it works fine :slight_smile: Is it possible that i want to use my pc without openvpn client b’cz i don’t need vpn on my pc just need pi-hole dns on my pc if yes please help me out to configure my vps accordingly all suggestions and recommendations are highly appreciated, thanks in advance :slight_smile:

**Comment by CrashenX** [comment]
Using Pi-hole on the open Internet without a VPN is dangerous. Pi-hole does not, or at least last I checked, support https and is designed to run on your home network. OpenVPN extends your home network. If you would like to run at home, you can install Pi-hole on a Raspberry Pi or low powered computer. The use case for this was largely for users who wanted Pi-hole on the go.
